# Generated by Django 3.0.5 on 2024-04-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjaman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='statuspeminjaman',
            field=models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan'), ('Konfirmasi', 'Konfirmasi')], max_length=50),
        ),
    ]
