# Generated by Django 3.0.5 on 2024-04-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kategoribuku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('bukuid', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('penulis', models.CharField(max_length=255)),
                ('penerbit', models.CharField(max_length=255)),
                ('tahunterbit', models.IntegerField()),
                ('tersedia', models.BooleanField(default=True)),
                ('kategoriid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kategoribuku.Kategoribuku')),
            ],
            options={
                'db_table': 'buku',
            },
        ),
    ]
